### ISSUE TITLE
Add input validation

### ISSUE THREAD

**Issue by jrfnl** [rmccue/Requests#593]
This is just an issue to track which classes have been reviewed for missing input validation and the associated PRs adding the input validation.

Input validation is being added to all entry point methods for each class with an `InvalidArgument` exception being thrown for invalid parameter types. As this _may_ break existing uses of Requests, this input validation needs to be added in the 2.0.0 release.

### Action list
- [x] `WpOrg\Requests\Auth\Basic` - PR #574
- [x] `WpOrg\Requests\Autoload` - No additional input validation needed, the `Autoload::load()` method should only ever by called by PHP itself.
- [x] `WpOrg\Requests\Cookie` - PR #609
- [x] `WpOrg\Requests\Cookie\Jar` - PR #610
- [x] `WpOrg\Requests\Hooks` - PR #573
- [x] `WpOrg\Requests\IdnaEncoder` - PR #592 (only typical entry point, other methods deemed unnecessary)
- [x] `WpOrg\Requests\Ipv6` - PR #601
- [x] `WpOrg\Requests\Iri` - PR #602
- [x] `WpOrg\Requests\Port` - Input validation was included when the class was introduced in PR #538
- [x] `WpOrg\Requests\Proxy\Http` - PR #611
- [x] `WpOrg\Requests\Requests` - PR #621
- [x] `WpOrg\Requests\Response` - PR #603
- [x] `WpOrg\Requests\Response\Headers` - PR #605
- [x] `WpOrg\Requests\Session` - PR #620
- [x] `WpOrg\Requests\Ssl` - PR #572
- [x] `WpOrg\Requests\Transport\Curl` - PR #629
- [x] `WpOrg\Requests\Transport\Fsockopen` - PR #629
- [x] `WpOrg\Requests\Utility\CaseInsensitiveDictionary` - No changes needed.
        - The `__construct()` method already has a type declared for the parameter.
        - The `offset*()` methods are part of `ArrayAccess()` and they should not be called directly, but only indirectly and when called that way, will receive the correct input type.
        - The remaining methods don't take parameters.
- [x] `WpOrg\Requests\Utility\FilteredIterator` - PR #604
- [x] `WpOrg\Requests\Utility\InputValidator` - Not applicable.
- [x] `WpOrg\Requests\Exception` - I'm going to leave this as-is. The important parameters are validated via the PHP native `Exception` class, that should be enough.
- [x] `WpOrg\Requests\Exception\ArgumentCount` - Only intended for internal use.
- [x] `WpOrg\Requests\Exception\Http` - Uses sensible defaults.
- [x] `WpOrg\Requests\Exception\InvalidArgument` - Only intended for internal use.
- [x] `WpOrg\Requests\Exception\Transport` - Does not contain methods.
- [x] `WpOrg\Requests\Exception\Transport\Curl` - Uses sensible defaults.
- [x] `WpOrg\Requests\Exception\Http\Status###` - No changes needed, these classes do not contain methods.
- [x] `WpOrg\Requests\Exception\Http\StatusUnknown` - Uses sensible defaults.

Note: the Requests native Exception classes are already exceptions, so rather than throwing _another_ exception on invalid input, these should defer to sensible default values when invalid input is passed.

**Comment by jrfnl** [comment]
Closing as all related PRs have been merged.
