### ISSUE TITLE
DRAFT Roadmap Requests 3.0

### ISSUE THREAD

**Issue by jrfnl** [rmccue/Requests#597]
This issue is intended to contain a tentative roadmap for things to be included/removed in Requests 3.0.

For now, the most important function of this issue is to contain an action list to keep track of follow-up actions from current PRs/issues, which need to be handled in a future major release.

### Action list
- [ ] Remove support for the deprecation notice silencing about use of the PSR-0 classes.
    I.e. remove support for the `REQUESTS_SILENCE_PSR0_DEPRECATIONS` constant.
    Related: https://github.com/WordPress/Requests/pull/519
- [ ] Make more classes final. See #866
- [ ] Drop support for PHP < 7.2.
- [ ] Replace input validation in methods with parameter type declarations wherever possible.
    Related: https://github.com/WordPress/Requests/issues/593 and #873
- [ ] Add return type declarations wherever possible (non-union types).

**Comment by jrfnl** [comment]
Updated the roadmap to remove references to dropping PHP 7.1 in favour of 7.2 and removing the uncertainty about doing this. As WordPress (the biggest Requests user) has now dropped support for PHP < 7.2, I expect we should be able to drop support for PHP < 7.2 in Requests as well.
