### ISSUE TITLE
Release version 1.6

### ISSUE THREAD

**Issue by rmccue** [rmccue/Requests#76]
Issues remaining for 1.6:
- [x] SSL certificates (security) in #63
- [x] Sessions (to match cookies) in #62
- [x] Small documentation issue in #33

The aim is to push the release out this week as soon as I have spare time. Also considering bumping to 2.0 given the size of the release, but we'll see.
